# This .gitpod.yml file is used to configure the Gitpod workspace.

# The 'image' field specifies the Docker image to be used for the workspace.
# The 'file' field under 'image' points to the Dockerfile that is used to build the Docker image.
image:
  file: .gitpod/Dockerfile

# The 'tasks' field specifies a list of commands that are run when the workspace is initialized.
# The 'init' field under 'tasks' specifies the command to be run before the main command.
# In this case, it downloads and installs 'yq', a command-line YAML processor, and runs several shell scripts.
tasks:
  - init: sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && sudo chmod a+x /usr/local/bin/yq && chmod +x ./dockerfiles/gitpodURL.sh && ./dockerfiles/gitpodURL.sh

# The 'ports' field specifies a list of ports that should be exposed in the workspace.
# Each item in the list can have a 'name', 'port', 'protocol', 'onOpen', and 'description'.
# 'name' is a human-readable name for the port.
# 'port' is the port number.
# 'protocol' is the protocol used (e.g., 'http', 'https').
# 'onOpen' specifies what should happen when the port is opened (e.g., 'open-preview', 'open-browser').
# 'description' provides additional information about the port.
ports:
  - name: Jenkins controller
    port: 8080
    protocol: http
    onOpen: open-preview
    description: The Jenkins Controller to use for the tutorials